alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias less='less -R'
alias ls='ls --color=auto'
alias la='ls -A'
alias ll='ls -Ahl'
alias neofetch='fastfetch'
alias tmux='tmux -u2'
alias vim='nvim'
