# Set status style
set -g status-fg colour66
set -g status-bg colour236

set -g status-left-length 40
set -g status-right-length 80

# Set key mapping for copy mode
setw -g mode-keys vi

# Set prefix to Ctrl-Space instead of Ctrl-b
unbind-key C-b
set-option -g prefix C-Space
bind-key Space send-prefix

# Rebind pane selection
unbind-key l
bind-key b last-window

bind-key h select-pane -L
bind-key j select-pane -U
bind-key k select-pane -D
bind-key l select-pane -R

# Rebind pane creation
unbind-key -

bind-key | split-window -v
bind-key - split-window -h
