#!/bin/python

import os
import subprocess


def get_disk_info():
    info = subprocess.check_output(
            "df -B 1M --output=target,avail,size | awk '/^\\/[[:space:]]/'",
            shell=True)

    _, disk_avail, disk_size, *_ = info.decode().strip().split()

    return disk_avail, disk_size


ONE_KIBIBYTE = 1024
DISK_SYMBOL = '\uF0A0'

disk_avail, disk_size = get_disk_info()

disk_avail = float(disk_avail) / ONE_KIBIBYTE
disk_size = float(disk_size) / ONE_KIBIBYTE

message = f'{DISK_SYMBOL} {disk_avail:.2f} GiB'

disk_size_one_percent = disk_size / 100

# disk capacity lower than or equal to 5%
if disk_avail <= disk_size_one_percent * 5:
    print(f'<span foreground="{os.getenv('_color_urgent')}">{message}</span>')
else:
    print(message)
