# Set variables
LIGHT_COLOR=white
DARK_COLOR=black
PRIMARY_COLOR=blue
SECONDARY_COLOR=brightblack

# Server options
set -as terminal-overrides ",xterm-256color:RGB"

# General options
set -g renumber-windows on
set -g base-index 1
set -g mouse on

# Set status style
set -g status-fg $LIGHT_COLOR
set -g status-bg $DARK_COLOR

set -g status-left-length 40
set -g status-right-length 80

set -g status-left "#[fg=$DARK_COLOR,bg=$PRIMARY_COLOR] #{session_name} #[fg=$PRIMARY_COLOR,bg=$SECONDARY_COLOR] #{user} #[default] "
set -g status-right " #{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,} #[fg=$PRIMARY_COLOR,bg=$SECONDARY_COLOR] #{=21:pane_title} #[fg=$DARK_COLOR,bg=$PRIMARY_COLOR] %F %r "

# Set key mapping for copy mode
set -g mode-keys vi

# Set prefix to Ctrl-Space instead of Ctrl-b
unbind C-b
set -g prefix C-Space
bind Space send-prefix

# Rebind pane selection
unbind l
bind b last

bind h selectp -L
bind j selectp -U
bind k selectp -D
bind l selectp -R

# Rebind kill window
unbind &
bind X confirm -p "kill-window #W? (y/n)" killw

# Rebind pane creation
unbind -

bind | splitw -v
bind - splitw -h
