Section "InputClass"
	Identifier "system-keyboard"
	MatchIsKeyboard "on"
	Option "XkbLayout" "us,de"
	Option "XkbModel" "pc104"
	# Disabled, switching with window manager
	# Option "XkbOptions" "grp:win_space_toggle"
EndSection
