#!/bin/python

import os
import subprocess


def get_mem_info():
    info = subprocess.run(['free', '-m'], capture_output=True).stdout
    lines = info.decode().splitlines()

    _, mem_total_gig, mem_used_gig, *_, mem_available_gig = lines[1].split()

    return mem_total_gig, mem_used_gig, mem_available_gig


ONE_KIBIBYTE = 1024
MEM_SYMBOL = '\U000F035B'

mem_total_gig, mem_used_gig, mem_available_gig = get_mem_info()

mem_total_gig = float(mem_total_gig) / ONE_KIBIBYTE
mem_used_gig = float(mem_used_gig) / ONE_KIBIBYTE
mem_available_gig = float(mem_available_gig) / ONE_KIBIBYTE

message = f'{MEM_SYMBOL} {mem_used_gig:.2f} GiB/{mem_available_gig:.2f} GiB'

mem_total_one_percent = mem_total_gig / 100

# memory lower than or equal to five percent
if mem_used_gig >= mem_total_one_percent * 95:
    print(f'<span foreground="{os.getenv('_color_urgent')}">{message}</span>')

    # memory lower than or equal to ten percent
elif mem_used_gig >= mem_total_one_percent * 90:
    print(f'<span foreground="{os.getenv('_color_warn')}">{message}</span>')
else:
    print(message)
